from_latest_tag = true
tag_prefix = "release-"
ignore_merge_commits = false
ignore_fixup_commits = false
branch_whitelist = ["main"]
pre = "snapshot.*"
skip_ci = "[skip ci]"

[commit_types]
chore = { omit_from_changelog = true }

[changelog]
path = "CHANGELOG.md"
authors = [
  { signature = "Thomas Seliger", username = "neovatar" }
]
