name: Release Creation

on:
  push:
    branches:
      - main
      - snapshot

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Run semrel
        uses: docker://ghcr.io/semrels/semrel:sha256-a111c90e47d521f6e31b1fcdb1a34bbb6d7ad720f3be62e46de9f095590ef7f0
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Load module manifest
        id: manifest
        run: |
          # create step outputs for the module.json properties we care about
          echo "version=$(jq -r '.version' module.json)" >> $GITHUB_OUTPUT
          echo "compatibility_minimum=$(jq -r '.compatibility.minimum' module.json)" >> $GITHUB_OUTPUT
          echo "compatibility_verified=$(jq -r '.compatibility.verified' module.json)" >> $GITHUB_OUTPUT
          echo "url=$(jq -r '.url' module.json)" >> $GITHUB_OUTPUT
          echo "manifest=$(jq -r '.manifest' module.json)" >> $GITHUB_OUTPUT
          echo "download=$(jq -r '.download' module.json)" >> $GITHUB_OUTPUT

      - name: Publish release
        uses: neovatar/foundry-package-release@v20260712144538
        with:
          token: ${{ secrets.FVTTP_TOKEN }}
          id: more-text-options
          version: ${{ steps.manifest.outputs.version }}
          manifest: ${{ steps.manifest.outputs.manifest }}
          notes: https://github.com/neovatar/more-text-options/blob/release-${{ steps.manifest.outputs.version }}/CHANGELOG.md
          compat_min: ${{ steps.manifest.outputs.compatibility_minimum }}
          compat_verified: ${{ steps.manifest.outputs.compatibility_verified }}
          dry_run: "false"
